# add your custom package feeds here
# If your required additional custom packages enable the feeds below
# By Remove the # symbols.

#src/gz openwrt_kiddin9 https://dl.openwrt.ai/packages-24.10/aarch64_generic/kiddin9
#src/gz kiddin9_packages https://dl.openwrt.ai/packages-24.10/aarch64_generic/packages
#src/gz kiddin9_base https://dl.openwrt.ai/packages-24.10/aarch64_generic/base
