src/gz immortalwrt_core https://immortalwrt.kyarucloud.moe/releases/24.10.6/targets/rockchip/armv8/packages
src/gz immortalwrt_base https://immortalwrt.kyarucloud.moe/releases/24.10.6/packages/aarch64_generic/base
src/gz immortalwrt_kmods https://immortalwrt.kyarucloud.moe/releases/24.10.6/targets/rockchip/armv8/kmods/6.6.133-1-23375d261da0c0e9da36857794905cf7
src/gz immortalwrt_luci https://immortalwrt.kyarucloud.moe/releases/24.10.6/packages/aarch64_generic/luci
src/gz immortalwrt_packages https://immortalwrt.kyarucloud.moe/releases/24.10.6/packages/aarch64_generic/packages
src/gz immortalwrt_routing https://immortalwrt.kyarucloud.moe/releases/24.10.6/packages/aarch64_generic/routing
src/gz immortalwrt_telephony https://immortalwrt.kyarucloud.moe/releases/24.10.6/packages/aarch64_generic/telephony
